### ISSUE TITLE
Dotnet core 2.2  MVC 下會死鎖

### ISSUE THREAD

**Issue by mayamoon** [cocosip/FastDFSCore#1]
public void ConfigureServices(IServiceCollection services)
        {
            services.AddLogging((logBuilder) =>
            {
                logBuilder.AddConsole();
                logBuilder.AddDebug();
              
            });
            var endpoints = InitFDFSConnection();
            services.AddFastDFSCore(c => {
                c.Trackers = endpoints;
                c.Charset = System.Text.UTF8Encoding.Default;
                c.ConnectionTimeout = 5;
                c.ConnectionLifeTime = 10;
                c.ScanTimeoutConnectionInterval = 10;
                c.TrackerMaxConnection = 50;
                c.StorageMaxConnection = 100;
                c.LoggerName = "FDFSLogger";
                c.TcpSetting = new TcpSetting
                {
                    QuietPeriodMilliSeconds = 100,
                    CloseTimeoutSeconds = 1,
                    WriteBufferHighWaterMark = 16777216,
                    WriteBufferLowWaterMark = 8388608,
                    SoRcvbuf = 1048576,
                    SoSndbuf = 1048576,
                    TcpNodelay = true,
                    SoReuseaddr = true
                };

            });
           
            services.AddCors(options => options.AddPolicy("*", p => p.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader().AllowCredentials()));
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1",
                    new OpenApiInfo
                    {
                        Version = "v1",
                        Title = "FastDFSUploadAPI",
                        Description = "FastDFSUploadAPI",
                        TermsOfService = new Uri("http://tempuri.org/terms")
                    }
                );
            });
            services.ConfigureSwaggerGen(c =>
            {
                c.CustomSchemaIds(x => x.FullName);
                var xmlFilePath = Path.Combine(PlatformServices.Default.Application.ApplicationBasePath,
                    $"{PlatformServices.Default.Application.ApplicationName}.xml");
                c.IncludeXmlComments(xmlFilePath);
            });

        }

 public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseCors("*");
            app.UseMvc();
            app.UseSwagger(c =>
            {
                c.PreSerializeFilters.Add((swagger, httpReq) =>
                {
                    swagger.Servers = new List<OpenApiServer> { new OpenApiServer { Url = $"{httpReq.Scheme}://{httpReq.Host.Value}".AppendPathSegment(httpReq.PathBase) } };
                });
            });
            app.UseSwaggerUI(c =>
            {
                c.DisplayRequestDuration();
                c.SwaggerEndpoint("v1/swagger.json", "V1 Docs");
            });
            app.ApplicationServices.ConfigureFastDFSCore();
        }

 /// <summary>
    /// FastDFSUpload
    /// </summary>
    [Route("api/[controller]"), Produces("application/json")]
    public class UploadController : Controller
    {
        private IFDFSClient client;
        public UploadController(IFDFSClient client)
        {
            this.client = client;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="fileName"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("[action]")]
        public async Task<ActionResult> GetFileInfo([FromQuery]string fileName)
        {
            var storageNode = await client.GetStorageNodeAsync(GetGroupName(fileName));
            var fdfsFileName = GetFdfsFileName(fileName);
            var fileInfo = await client.GetFileInfo(storageNode, fdfsFileName).ConfigureAwait(false);

            return Ok(fileInfo);
        }
      }
调用第一次成功,能返回文件信息.再次调用就卡住了

**Comment by cocosip** [comment]
@mayamoon  你用的是最新版本的吗?你那边有更详细的一些环境或者其他的一些说明吗？
我这边用 AspNetCore2.2进行了测试,发现没有出现死锁问题 。
![image](https://user-images.githubusercontent.com/9337837/65755881-8e210600-e146-11e9-9272-299ca4940e93.png)
![image](https://user-images.githubusercontent.com/9337837/65755936-aa24a780-e146-11e9-9f77-e09c8d6de47b.png)

**我用了一个数量计数器，每次查询+1 ，效果如下:**

![image](https://user-images.githubusercontent.com/9337837/65756170-1acbc400-e147-11e9-869c-b913c93b6c34.png)

**Comment by mayamoon** [comment]
我的.NET CORE 程序配置文件加載錯亂了. Sorry
