### ISSUE TITLE
超过7M左右的文件，使用DownloadFileAsync下载文件流时假死

### ISSUE THREAD

**Issue by chunln** [cocosip/FastDFSCore#12]
下载超过7M左右的文件时，使用DownloadFileAsync下载文件流时线程阻塞，无返回结果！
但使用DownloadFileEx可以正常下载文件。
FastDFSCore:1.4.0
FastDFSCore.Transport.DotNetty:1.4.0
FastDFSCore.Transport.SuperSocket:1.4.0
.netcore 3.1

**Comment by cocosip** [comment]
> 下载超过7M左右的文件时，使用DownloadFileAsync下载文件流时线程阻塞，无返回结果！
> 但使用DownloadFileEx可以正常下载文件。
> FastDFSCore:1.4.0
> FastDFSCore.Transport.DotNetty:1.4.0
> FastDFSCore.Transport.SuperSocket:1.4.0
> .netcore 3.1

该问题主要出现在SuperSocket传输上,如果使用DotNetty是不会受到影响的。
SuperSocket对每个包的接收的最大长度有限制, 之前的SuperSocket版本不支持配置,新的预览版已经支持。
https://github.com/cocosip/FastDFSCore/commit/34e068727a3b55b6bc601e45e938c965e5d94f5b

**Comment by chunln** [comment]
> > 下载超过7M左右的文件时，使用DownloadFileAsync下载文件流时线程阻塞，无返回结果！
> > 但使用DownloadFileEx可以正常下载文件。
> > FastDFSCore:1.4.0
> > FastDFSCore.Transport.DotNetty:1.4.0
> > FastDFSCore.Transport.SuperSocket:1.4.0
> > .netcore 3.1
> 
> 该问题主要出现在SuperSocket传输上,如果使用DotNetty是不会受到影响的。
> SuperSocket对每个包的接收的最大长度有限制, 之前的SuperSocket版本不支持配置,新的预览版已经支持。
> [34e0687](https://github.com/cocosip/FastDFSCore/commit/34e068727a3b55b6bc601e45e938c965e5d94f5b)

> > 下载超过7M左右的文件时，使用DownloadFileAsync下载文件流时线程阻塞，无返回结果！
> > 但使用DownloadFileEx可以正常下载文件。
> > FastDFSCore:1.4.0
> > FastDFSCore.Transport.DotNetty:1.4.0
> > FastDFSCore.Transport.SuperSocket:1.4.0
> > .netcore 3.1
> 
> 该问题主要出现在SuperSocket传输上,如果使用DotNetty是不会受到影响的。
> SuperSocket对每个包的接收的最大长度有限制, 之前的SuperSocket版本不支持配置,新的预览版已经支持。
> [34e0687](https://github.com/cocosip/FastDFSCore/commit/34e068727a3b55b6bc601e45e938c965e5d94f5b)

请教下，两种传输方式有什么优缺点呢？

**Comment by cocosip** [comment]
> > > 下载超过7M左右的文件时，使用DownloadFileAsync下载文件流时线程阻塞，无返回结果！
> > > 但使用DownloadFileEx可以正常下载文件。
> > > FastDFSCore:1.4.0
> > > FastDFSCore.Transport.DotNetty:1.4.0
> > > FastDFSCore.Transport.SuperSocket:1.4.0
> > > .netcore 3.1
> > 
> > 
> > 该问题主要出现在SuperSocket传输上,如果使用DotNetty是不会受到影响的。
> > SuperSocket对每个包的接收的最大长度有限制, 之前的SuperSocket版本不支持配置,新的预览版已经支持。
> > [34e0687](https://github.com/cocosip/FastDFSCore/commit/34e068727a3b55b6bc601e45e938c965e5d94f5b)
> 
> > > 下载超过7M左右的文件时，使用DownloadFileAsync下载文件流时线程阻塞，无返回结果！
> > > 但使用DownloadFileEx可以正常下载文件。
> > > FastDFSCore:1.4.0
> > > FastDFSCore.Transport.DotNetty:1.4.0
> > > FastDFSCore.Transport.SuperSocket:1.4.0
> > > .netcore 3.1
> > 
> > 
> > 该问题主要出现在SuperSocket传输上,如果使用DotNetty是不会受到影响的。
> > SuperSocket对每个包的接收的最大长度有限制, 之前的SuperSocket版本不支持配置,新的预览版已经支持。
> > [34e0687](https://github.com/cocosip/FastDFSCore/commit/34e068727a3b55b6bc601e45e938c965e5d94f5b)
> 
> 请教下，两种传输方式有什么优缺点呢？

并没有太大的差别,最初的时候直接引用的DotNetty, DotNetty 基本上不会再更新了，就转SuperSocket上,SuperSocket后续的支持会更好一点。

**Comment by chunln** [comment]
感谢😁
