### ISSUE TITLE
使用FixChunkedStream分块异常

### ISSUE THREAD

**Issue by SunGram** [cocosip/FastDFSCore#4]
当文件大于30mb，上传成功，但下载的文件损坏

**Comment by cocosip** [comment]
在测试该问题时,我这边并没有重现。能提供一些更详细的东西吗?比如你使用的下载器这块的代码。
文件下载这块是这样实现的 : 当开始下载的时候,会有一个独立的线程在运行,每当接收到服务器端返回的 二进制数据就会写入到指定的Stream中。
详细的写法可以参考: 

- 读取服务器端返回数据
https://github.com/cocosip/FastDFSCore/blob/master/src/FastDFSCore/Client/Common/Connection.cs#L255
- 将数据写入本地流
https://github.com/cocosip/FastDFSCore/blob/master/src/FastDFSCore/Client/Common/Download/BaseDownloader.cs

**Comment by SunGram** [comment]
不采用chunkedstream，直接使用默认上传，文件是正常。
查看fastdfs的存储块中文件，已经损坏。
目前通过.net core 3.1 webapi 调用fastdfscore将临时文件夹的文件推送到fastdfs。

**Comment by cocosip** [comment]
chunkedstream 是DotNetty自带的, FastDFSCore 用的 FixChunkedStream 仅仅只是在 chunkedstream 上面添加了一个异步转同步的方法来避免死锁问题, 并没有对DotNetty做过多的改动。
我这边暂时没办法重现, 看看你那边是否能找找原因。比如多线程对同个流的读写,或者网速比较慢造成tcp的超时。如果方便的话贴一下代码。

**Comment by SunGram** [comment]
好的，谢谢你的帮助。
我会用你的示例测试下
---api

                    var fastdfsPath = await FastdfsManager.MoveFileAsync(_logger, _fdfsClinet, _diskConfig, filePath, fileExt).ConfigureAwait(false);

                    if (string.IsNullOrEmpty(fastdfsPath))
                    {
                        throw new ErrException("文件入库失败，请重试");
                    }

--
 public static async Task<string> MoveFileAsync(ILogger _logger, IFDFSClient fdfsClinet, DiskConfig diskConfig, string filePath, string fileExt = null)
        {
            try
            {

                var storageNode = await fdfsClinet.GetStorageNodeAsync(diskConfig.GroupName).ConfigureAwait(false);

                var fdfsPath = await fdfsClinet.UploadFileAsync(storageNode, filePath);

                return fdfsPath;
            }
            catch (Exception ex)
            {
            }
        }
