### ISSUE TITLE
如何支持reconnect？

### ISSUE THREAD

**Issue by ghost** [cocosip/FastDFSCore#8]
RT

**Comment by cocosip** [comment]
`FastDFSOption` 中的 `TcpSetting` 节点下的 `EnableReConnect ` 控制着是否启用重连机制。
[FastDFSOption代码](https://github.com/cocosip/FastDFSCore/blob/master/src/FastDFSCore/FDFSOption.cs#L66)
重连的实现代码可以参考: [DotNettyConnection中的代码实现](https://github.com/cocosip/FastDFSCore/blob/master/src/FastDFSCore.Transport.DotNetty/Transport/DotNettyConnection.cs)

最近对通讯这块进行了分离,`DotNetty`这块的代码以后可以用其他通讯库,如 `SuperSocket`替代。
